# Generated by Django 4.1.3 on 2022-12-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "shortcode",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("url", models.CharField(max_length=256)),
                ("img_url", models.CharField(max_length=700)),
                ("caption", models.CharField(blank=True, max_length=1200, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "product_label",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "seller_username",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "seller_phonenumber",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("post_date", models.DateTimeField()),
                ("price", models.CharField(blank=True, max_length=256, null=True)),
                ("likes", models.IntegerField()),
                ("comments", models.IntegerField()),
                ("is_ads", models.BooleanField(blank=True, null=True)),
                ("is_video", models.BooleanField()),
                ("is_single_product", models.BooleanField(blank=True, null=True)),
                ("is_sold", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostOwner",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("followers", models.IntegerField()),
                ("total_post", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ScrapingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraping_date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.postowner",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileAnalytic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("followers", models.IntegerField()),
                ("total_post", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.postowner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostSideCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sidecard_len", models.IntegerField()),
                ("display_url", models.CharField(max_length=256)),
                ("is_video", models.BooleanField()),
                ("video_url", models.CharField(max_length=700)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.post",
                    ),
                ),
            ],
        ),
    ]
