# Generated by Django 4.1.3 on 2022-12-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_url", models.CharField(max_length=256)),
                ("shortid", models.CharField(max_length=256)),
                ("thumbnail_url", models.CharField(max_length=700)),
                ("caption", models.CharField(max_length=1200)),
                ("product_name", models.CharField(max_length=256)),
                ("seller_username", models.CharField(max_length=256)),
                ("post_date", models.DateTimeField()),
                ("price", models.CharField(max_length=256)),
                ("likes", models.IntegerField()),
                ("comments", models.IntegerField()),
                ("is_ads", models.BooleanField()),
                ("is_video", models.BooleanField()),
                ("is_single_product", models.BooleanField()),
                ("is_sold", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PostOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_username", models.CharField(max_length=256)),
                ("owner_followers", models.IntegerField()),
                ("owner_total_posts", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileAnalytic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("followers", models.IntegerField()),
                ("total_posts", models.IntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.postowner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostSideCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sidecard_len", models.IntegerField()),
                ("display_url", models.CharField(max_length=256)),
                ("is_video", models.BooleanField()),
                ("video_url", models.CharField(max_length=700)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instabarkas.post",
                    ),
                ),
            ],
        ),
    ]
