# Generated by Django 4.1.3 on 2022-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instabarkas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsidecard",
            name="video_url",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
